- hosts: all
  tasks:
  - name: Test ping
    ping:
  - name: Install prerequisites
    command:
      cmd: sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
  - name: Add GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add docker repo
    command:
      cmd: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - name: Install docker
    shell: |
      apt-cache policy docker-ce
      sudo apt -y install docker-ce
  - name: Show docker info
    command:
      cmd: sudo systemctl status docker
    register: shell_result
  - debug:
      var: shell_result.stdout_lines
  - name: Run docker without sudo 
    shell: |
      sudo usermod -aG docker root
