{
 "title": "Practice 4",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max scrape duration",
   "type": "timeseries",
   "description": "Max scrape duration for each job",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds) by (job)"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "timeseries",
   "description": "Up time for each instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  { "title": "MongoDB Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current connections to MongoDB",
   "type": "timeseries",
   "description": "Current number of connections to MongoDB server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}"
    }
   ]
  },
  {
   "title": "CRUD in MongoDB",
   "type": "timeseries",
   "description": "Delete, insert, return, update in MongoDB",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    { "expr": "mongodb_ss_metrics_document" }
   ]
  },
  {
   "title": "Page faults count",
   "type": "timeseries",
   "description": "Page faults in MongDB server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "mongodb_ss_extra_info_page_faults"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "instance" },
  {
   "title": "CPU load of monitor machine",
   "type": "gauge",
   "description": "Not idle CPU in monitor machine in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter:9100\"}[2m])) * 100) "
    }
   ]
  },
  {
   "title": "CPU load of MongoDB server",
   "type": "gauge",
   "description": "Not idle CPU in MongoDB server in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"54.90.221.86:9100\"}[2m])) * 100) "
    }
   ]
  },
  {
   "title": "CPU load of Nginx server",
   "type": "gauge",
   "description": "Not idle CPU in Nginx server in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"18.212.78.52:9100\"}[2m])) * 100) "
    }
   ]
  },
  {
   "title": "CPU load of Flask server",
   "type": "gauge",
   "description": "Not idle CPU in Flask server",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"54.90.221.86:9100\"}[2m])) * 100) "
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node\"}[$__rate_interval])"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RAM usage of monitor machine",
   "type": "gauge",
   "description": "RAM used in monitor machine in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}) / (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM usage of MongoDB server",
   "type": "gauge",
   "description": "RAM used in MongoDB server in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"54.90.221.86:9100\"} - node_memory_MemFree_bytes{instance=\"54.90.221.86:9100\"}) / (node_memory_MemTotal_bytes{instance=\"54.90.221.86:9100\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM usage of Nginx server",
   "type": "gauge",
   "description": "RAM used in  Nginx server in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"18.212.78.52:9100\"} - node_memory_MemFree_bytes{instance=\"18.212.78.52:9100\"}) / (node_memory_MemTotal_bytes{instance=\"18.212.78.52:9100\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM usage of monitor machine",
   "type": "gauge",
   "description": "RAM used in monitor machine in 2m",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}) / (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} )) * 100"
    }
   ]
  }
 ]
}