---
- name: Install Nginx
  hosts: local
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /home/hvanh
    app_root: html_demo_site-main
  tasks:
    - name: Clone code
      ansible.builtin.git:
        repo: https://github.com/hvanh2122/html_demo.git
        dest: ./html_demo
        clone: yes
        force: yes

    - name: Chmod
      file:
        path: ./html_demo
        mode: '7777'
        recurse: yes

    - name: Update apt cache and install Nginx
      apt: 
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Configue Nginx
      copy:
        src: ./html_demo/ngnix.cfg
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Apply Nginx template 
      template: 
        src: ./html_demo/ngnix.cfg
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx
    
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Remove file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
