- name: Pull image
  command:
    cmd: docker pull haitranquangofficial/graduation:parser
- name: Run image
  command:
    cmd: docker run -d haitranquangofficial/graduation:parser
  register: shell_result
- debug:
    var: shell_result.stdout_lines