---  
- name: Install latest version of Apache        
  apt: name=apache2 update_cache=yes state=latest   

- name: Start apache service  
  service: name=apache2 state=started enabled=yes   
  
- name: Create Apache Document Root  
  file:   
    path: "/var/www/{{ http_host }}"    
    state: directory   
    owner: "ansible"  
    group: "ansible"   
    mode: '0755'     
   
- name: Set up Apache VirtualHost    
  template:  
    src: "files/apache.conf.j2"  
    dest: "/etc/apache2/sites-available/{{ http_conf }}"   
    owner: root   
    group: root  
    mode: u=rw,g=r,o=r    
