version: "3.9"
services:
  web_mongo:
    build: ./mongo
  web_python:
    build: ./python
    depends_on:
      - "web_mongo"
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: http.access
        fluentd-async: "true"
  web_nginx:
    build: ./nginx
    depends_on:
      - "web_python"
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 80:80
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
