version: '3.0'

services:
  fluentd:
    build: .
    restart: always
    container_name: fluentd_vt
    ports:
      - 24224:24224
      - 5140:5140
      - 24224:24224/udp
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
