{
 "title": "Node",
 "time": { "from": "2022-06-09T13:22:46.855Z", "to": "2022-06-09T13:32:38.053Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"user\"}[300s]) * 100"
    }
   ]
  },
  {
   "title": "CPU time by services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[10m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{label_name}}" },
    { "expr": "node_memory_Active_bytes" }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_filesystem_size_bytes" },
    {
     "expr": "node_filesystem_size_bytes - node_filesystem_free_bytes"
    }
   ]
  }
 ]
}