services:
   web: 
      image: nginx:1.22.0-alpine    
      volumes:   
         - ./nginx/nginx.conf:/tmp/nginx.conf    
      environment:  
         - FLASK_SERVER_ADDR=backend:9091   
      command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      ports:  
         - 80:80  
      depends_on:  
         - backend  
   backend:   
       build: flask   
       environment:   
         - FLASK_SERVER_PORT=9091    
       volumes:   
         - ./flask:/src   
       depends_on:   
         - mongo   
   mongo:   
       image: mongo:5.0.0     